export { replaceOperation } from './replaceOperation'
export { checkExpression } from './checkExpression'
export { checkAddToDisplay } from './checkAddToDisplay'
export { changeSing } from './changeSing'
export { checkInputExpression } from './checkInputExpression'
